<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'normal',
);
## END OF AUTOGENERATED OPTIONS

return array (
    array (
        'label' => 'Dashboard',
        'icon' => 'fa-home',
        'url' => '/exalutions/dashboard',
        'formattedUrl' => '/exalutions/index.php?r=exalutions/dashboard',
    ),
    array (
        'label' => 'Banner',
        'icon' => 'fa-cogs',
        'url' => 'exalutions/banner/index',
        'formattedUrl' => '/exalutions/index.php?r=exalutions/banner/index',
    ),
    array (
        'label' => 'Machine',
        'icon' => 'fa-rocket',
        'url' => '/exalutions/machine/index',
        'state' => 'collapsed',
        'formattedUrl' => '/exalutions/index.php?r=exalutions/machine/index',
    ),
    array (
        'label' => 'Spare Parts',
        'icon' => 'fa-archive',
        'url' => '/exalutions/SparePart/index',
        'state' => 'collapsed',
        'formattedUrl' => '/exalutions/index.php?r=exalutions/SparePart/index',
    ),
    array (
        'label' => 'Ink',
        'icon' => 'fa-adjust',
        'url' => '/exalutions/Ink/index',
        'state' => 'collapsed',
    ),
    array (
        'label' => 'Gallery',
        'icon' => 'fa-file-image-o',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'Photos',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Videos',
                'icon' => '',
                'url' => '#',
            ),
        ),
        'state' => 'collapsed',
    ),
    array (
        'label' => 'Downloads',
        'icon' => 'fa-cloud-download',
        'url' => '/exalutions/Download/index',
    ),
    array (
        'label' => 'Contact',
        'icon' => 'fa-phone',
        'url' => '/exalutions/Contact/update&id=1',
    ),
);